### PR TITLE
APA102 library

### PR DESCRIPTION
**Pull request by DoronShapiro**
Follows the WS2812 spec

### CODE REVIEW

**Comment by cat-haines** [comment]
We've got a task in our backlogs to add a .configure() method to the WS2812 class, and it would be great to it see here as well. The configure method should take zero parameters, return this, and configure the spi object passed into the constructor. 

This should let you do the following:

``` squirrel
pixels <- APA102(hardware.spi257, 5)
    .configure()
    .fill([100,0,100])
    .draw();
```

**Comment by ersatzavian** [comment]
If you want, you could add Tony's simpler WS2812 Examples to the examples folder... the Neoweather code does make for a useful finished thing, but it's a bit of a large ugly creature. 

https://electricimp.com/docs/tails/ws2812/

**Comment by DoronShapiro** [comment]
All updated with the light show example and ready for another look

**Comment by DoronShapiro** [comment]
Ready for review

**Comment by cat-haines** [comment]
I would remove the shouldDraw option from the constructor. Adding a `configure` method encourages developers to not preconfigure the spi bus, meaning it will likely not be initialized during the first draw.

If you make that change, you should add a note to the docs saying "you should call draw immediately after the constructor (if a preconfigured spibus was passed in) or after configure (if you're using the configure method)"

Other than that, it looks really good :ok_hand:

**Comment by DoronShapiro** [comment]
Ready for review

**Comment by ersatzavian** [comment]
I like it!

**Pull request merged**
